#server.port=8080
#demo.ribbon.listOfServers=http://localhost:8081,http://localhost:8082
#
#
#lru.capacity=2

#spring.redis.host=47.100.61.70
#spring.redis.port=6379

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: a123

#redisson:
#  singleServerConfig:
#    address: 127:0:0:1:6379


